#
# @author      David Lilue <dvdalilue@gmail.com> --- 09-10444
#	       Verónica Liñayo <vlinayo@gmail.com> --- 08-10615
# @version     1.0          
# @since       2014-01-07
#

all: 
	javac LongOpt.java Getopt.java GetoptDemo.java

docs: 
	javadoc -author -version -public Getopt.java LongOpt.java

clean:
	\rm -f *.class *.*~
